### ISSUE TITLE
Question: How do I build this?

### ISSUE THREAD

**Issue by ultrasound1372** [jpcima/miniopl3#2]
I'm interested to mess with this, even if the VST preset operation isn't quite complete. However I am unsure what I need to build this. I am on Windows and will be using the VST version within the reaper DAW. I have the latest Visual Studio community with c++ build tools, and wsl running Ubuntu 18.04 in case I need to build it on linux. I cna't seem to build using the makefile on Windows at all, so I launched WSL and tried make in the root, make plugins in the root, and make install-user from plugin/MiniOPL3, each time getting this error from make.
```
make[1]: *** No rule to make target '../../build/miniopl3/sources/plugin/PluginMiniOPL3.cpp.o', needed by '../../bin/min
iopl3.lv2/miniopl3_dsp.dll'.  Stop.
```
It used to say .so but I had defined the environment variable WINDOWS=true because I saw that check. I am inexperienced with c compilers, and right now only have build-essential that I can use for building. What are the dependencies I might need to build this?

**Comment by jpcima** [comment]
Hello,
The WSL compiler from build-essential is going to target Linux, so that won't work, and setting `WINDOWS=true` is not going to change anything to this.

My guess is one should build an environment based MSYS2, and then install MinGW compiler suite in it, that targets Windows.

But wait a little bit, I'll copy over some build configs I have in similar projects, and there will be some binary builds for download.

**Comment by jpcima** [comment]
There are currently a pair of continuous builds ready.
Below, two links of some Windows VST, 32 and 64-bit respectively.

https://github.com/jpcima/miniopl3/releases/download/automatic/miniopl3-win32.zip
https://github.com/jpcima/miniopl3/releases/download/automatic/miniopl3-win64.zip
